Repository nextcloud-libraries/stylelint-config, pull requests merged in 2022-01, with the labels that each got.

#25 Do not lint svg files
  index.js
Labels: 3. to review, bug

#26 Fix stylelint scss config
  index.js
  package-lock.json
  package.json
Labels: 3. to review

#27 Bump stylelint and associated
  package-lock.json
  package.json
Labels: 3. to review, enhancement, dependencies

#29 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies
